spring:
  # redis 配置
  redis:
    host: 1.14.43.96
    password: XXJ991228
  cache:
    cache-names: ["user_cache"]
    type: redis
  # mysql 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.43.96:3306/DateOrNot
    username: root
    password: 12345678
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
# 服务器端口
server:
  port: 8000
debug: false
# 匹配设置参数
matchpool:
  pool-count: 1
  compressor:
    enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
