# 对空格的要求很高
# 可以注入到我们的配置类中，可以直接给实体类赋值

# 普通的key-value
k: v

# 对象
student:
  name: dengqi
  age: 21

# 行内写法
student1: {name: degqi, age: 21}

# 数组
pets:
  - cat
  - dog
  - pig
pets2: [cat.dog,pig]

# 更改项目端口号
server:
  port: 8081

# 可以通过debug: true 查看哪写自动配置类生效、未生效