spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.14.43.96:3306/DateOrNot?useUnicode=false&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 12345678

server:
  port: 8888
  servlet:
    context-path: /dateornot


mybatis:
  mapper-locations: com/dateornotbackend/mapper/*.xml

logging:
  level:
    com:
      dateornotbackend:
        mapper: debug

pagehelper:
  helper-dialect: mysql
